# Generated by Django 3.0.8 on 2020-09-20 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbibi', '0002_auto_20200920_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbi',
            name='hobbi',
            field=models.ManyToManyField(related_name='hobbi', to=settings.AUTH_USER_MODEL),
        ),
    ]
