# Generated by Django 3.0.8 on 2020-09-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbibi', '0003_hobbi_hobbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=35),
            preserve_default=False,
        ),
    ]
