# Generated by Django 3.0.8 on 2020-09-21 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbibi', '0004_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbi',
            name='hobbi',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbibi.Hobbi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
